version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=backend.config.settings.prod
    command: >
      sh -c "
        python manage.py makemigrations --no-input &&
        python manage.py migrate --no-input &&
        gunicorn backend.config.wsgi:application --bind 0.0.0.0:8000
      "
    expose:
      - "8000"

  nginx:
    image: nginx:stable-alpine
    ports:
      -"8080:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend